<a href="https://colab.research.google.com/github/aadityane93/Toxic_Comments_Sentiment_Analysis/blob/aaditya/1_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Toxic Comment Classification

## Kaggle DataSet

In [ ]:
#https://www.kaggle.com/c/jigsaw-toxic-comment-classification-challenge

## Imports

In [ ]:
import pandas as pd

## Load Data

In [ ]:
test_labels = pd.read_csv("test_labels.csv")
test_labels.head()

,id,toxic,severe_toxic,obscene,threat,insult,identity_hate
0,00001cee341fdb12,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0
1,0000247867823ef7,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0
2,00013b17ad220c46,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0
3,00017563c3f7919a,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0
4,00017695ad8997eb,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0

In [ ]:
test_df = pd.read_csv(
    "test.csv",
    engine="python",
    on_bad_lines="skip"
)

test_df = test_df.dropna(subset=["comment_text"])
test_df["comment_text"] = test_df["comment_text"].astype(str)

test_df.head()

                 id                                       comment_text
0  00001cee341fdb12  Yo bitch Ja Rule is more succesful then you'll...
1  0000247867823ef7  == From RfC == \n\n The title is fine as it is...
2  00013b17ad220c46  " \n\n == Sources == \n\n * Zawe Ashton on Lap...
3  00017563c3f7919a  :If you have a look back at the source, the in...
4  00017695ad8997eb          I don't anonymously edit articles at all.

In [ ]:
train_df = pd.read_csv(
    "train.csv",
    engine="python",
    on_bad_lines="skip"
)

train_df = train_df.dropna(subset=["comment_text"])
train_df["comment_text"] = train_df["comment_text"].astype(str)

train_df.head()

,id,comment_text,toxic,severe_toxic,obscene,threat,insult,identity_hate
0,0000997932d777bf,Explanation\nWhy the edits made under my usern...,0,0,0,0,0,0
1,000103f0d9cfb60f,D'aww! He matches this background colour I'm s...,0,0,0,0,0,0
2,000113f07ec002fd,"Hey man, I'm really not trying to edit war. It...",0,0,0,0,0,0
3,0001b41b1c6bb37e,"""\nMore\nI can't make any real suggestions on ...",0,0,0,0,0,0
4,0001d958c54c6e35,"You, sir, are my hero. Any chance you remember...",0,0,0,0,0,0